/*
 * generated by Xtext 2.29.0
 */
package de.fraunhofer.ipa.rossystem.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRosSystemScopeProvider extends DelegatingScopeProvider {
}
