/*
 * generated by Xtext 2.30.0
 */
package de.fraunhofer.ipa.rossystem;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class RosSystemStandaloneSetup extends RosSystemStandaloneSetupGenerated {

    public static void doSetup() {
        new RosSystemStandaloneSetup().createInjectorAndDoEMFRegistration();
    }
}
